CREATE DATABASE IF NOT EXISTS testdb;
use testdb;

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT VARCHAR(255),
    EMPLOYEE_NAME VARCHAR(255),
    EMPLOYEE_SALARY VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

